### PR TITLE
[FEATURE] Declare compatibility with Symfony 6

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by o-ba** [comment]
Hi thanks for this PR. Is there a specific reason why you want to declare this compatibility?

Even if the tests are passing. I'm not sure if tailor is yet compatible with Symfony 6. Have to check this in more detail.

**Comment by oliverklee** [comment]
> Is there a specific reason why you want to declare this compatibility?

Nothing in particular. Just for getting the latest and greatest features and bug fixes.

**Comment by o-ba** [comment]
Let's until symfony 6 is officially released.

**Comment by oliverklee** [comment]
@o-ba Symfony 6 has been released. Please let's get this in.

**Comment by o-ba** [comment]
Thanks for the reminder. I haven't had the time to test tailor with symfony 6 yet, but will do soon. Have you successfully run tailor with symfony 6?

**Comment by oliverklee** [comment]
> Have you successfully run tailor with symfony 6?

No, I haven't tried that yet.

**Comment by lolli42** [comment]
Ping. This is more important now that core v12 requires symfony 6.

**Review by lolli42 — APPROVED** [review]

**Comment by lolli42** [comment]
I would be fine with: Accept it for now, fix later if something goes wrong?
Reason: It's kinda hard to test as such currently, since we'd have to actively release something with tailor based on core v12 to see if something goes wrong. It might be easier to just try and then fix in case it crashes?

**Comment by oliverklee** [comment]
> Accept it for now, fix later if something goes wrong?

I'd be fine with that as well.

**Comment by o-ba** [comment]
Finally found the time to test tailor locally with v6. It seems to work without any adaptations. Therefore, I'll merge corresponding PR now.

**Pull request merged**
